// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoA4ETyWAfo1Df_vcARWXomliCShuI',
    appId: '1:322644172:web:8aced64b749003b0e69',
    messagingSenderId: '3222264172',
    projectId: 'chatapp-50493',
    authDomain: 'chatapp-50493.firebaseapp.com',
    storageBucket: 'chatapp-50493.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxw4RX8ytMFAuO-clQKSJdjZoOTM8',
    appId: '1:32264172:android:e7dee76dff2e07f63b0e69',
    messagingSenderId: '3222644172',
    projectId: 'chatapp-50493',
    storageBucket: 'chatapp-50493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp5zzWY7HnCst2HjiRiYz70ILp3U',
    appId: '1:322644172:ios:0c62ba6d0e293b0e69',
    messagingSenderId: '322224172',
    projectId: 'chatapp-50493',
    storageBucket: 'chatapp-50493.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp5zzWY7HnCsJdLiRiYz70ILp3U',
    appId: '1:32224172:ios:12e8686db7ac3b0e69',
    messagingSenderId: '322644172',
    projectId: 'chatapp-50493',
    storageBucket: 'chatapp-50493.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
